CUDNN:
  GPU: '0'
DATASET:
  IMAGE_SIZE:
    ORI: 280
    H: 32
    W: 160   # resized width: 160
  IMAGE_ROOT: "/home/ubuntu/hks/ocr/360wan_data/images"
  CHAR_FILE: 'datasets/char_map/char_std_6736.txt'
  LABELS_FILE: {'TRAIN': 'datasets/labels/train.txt',
              'VAL': 'datasets/labels/test.txt'}
TRAIN:
  EPOCH: 40
  BATCH: 32
  SHUFFLE: True
  WORKERS: 0
  RESUME:
    IS_RESUME: False
    MODEL_SAVE:
  OPTIMIZER: 'adam'
  LR: 0.0001
  LR_STEP: [15, 30]
  LR_FACTOR: 0.1
  SHOW_STEP: 20

TEST:
  BATCH: 32
  SHUFFLE: False
  WORKERS: 8
MODEL:
  NAME: 'crnn_ctc'
  BACKBONE: 'densenet'#['resnet18','resnet34','resnet50','resnet101','resnet152','densenet','mobilenet_v2','mobileNet_v3_Large','mobileNet_v3_Small']
  NUM_CLASSES: 6736
  LSTM_NUM_LAYER: 2
  LSTM_NUM_HIDDEN: 256

