CUDNN:
  GPU: '1'
DATASET:
  IMAGE_SIZE:
    ORI: 280
    H: 32
    W: 160   # resized width: 160
  IMAGE_ROOT: "/home/simple/mydemo/ocr_project/word_recogization/id_datas/split_text_idcard"
  CHAR_FILE: 'datasets/char_map/char_std_6031.txt'
  LABELS_FILE: {'TRAIN': 'datasets/labels/generate_labels_train.csv',
                'VAL': 'datasets/labels/generate_labels_val.csv'}
TRAIN:
  EPOCH: 40
  BATCH: 32
  SHUFFLE: True
  WORKERS: 0
  RESUME:
    IS_RESUME: True
    MODEL_SAVE: '/home/ubuntu/hks/ocr/pytorch_rcnn_ctc/save_outputs/2020-06-08 04:21:50_dev_lstm_2layer_256/models_saved/epoch_7_acc_0.9921.pth'
  OPTIMIZER: 'adam'
  LR: 0.0001
  LR_STEP: [5, 8]
  LR_FACTOR: 0.1
  SHOW_STEP: 20

TEST:
  BATCH: 32
  SHUFFLE: False
  WORKERS: 8
MODEL:
  NAME: 'crnn_ctc'
  BACKBONE: 'resnet18'#['resnet18','resnet34','resnet50','resnet101','resnet152','densenet','mobilenet_v2','mobileNet_v3_Large','mobileNet_v3_Small']
  NUM_CLASSES: 6031
  LSTM_NUM_LAYER: 2
  LSTM_NUM_HIDDEN: 256

